name = "MyFirstPackage"
uuid = "80fd3c76-f75e-41c4-8516-6b2152ddb9ec"
version = "1.0.0-DEV"
authors = ["Xiwei Pan"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
BenchmarkTools = "1.6.0"
LinearAlgebra = "1.12.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
